# Copyright 2024 Brazona Tech

##################################################################################################
# Details service
##################################################################################################
# Publica os namespace no ambiente kubernetes
---

apiVersion: v1
kind: Namespace
metadata:
  name: development

---

apiVersion: v1
kind: Namespace
metadata:
  name: homologation

--- 

apiVersion: v1
kind: Namespace
metadata:
  name: staging

--- 

apiVersion: v1
kind: Namespace
metadata:
  name: production

